### ISSUE TITLE
Chat Formatting Issues

### ISSUE THREAD

**Issue by KiroKite** [nhulston/ChatCore#2]
Hello, hope you're doing well.

I switched to this plugin for its features, hover w/ mouse chat, and alot of features. But, as I started to use the plugin, I found issues, these could be bugs.

1) **No custom colour codes**, atleast that I know how to format.
 - This means stuff like "&#00000Banana" won't work. ( That was just an example, I know for sure that isn't isnt an actual hex colour code )
 
2) **No placeholder support.**
 - Fixed. My bad.
 
I am sure, these are easy fixes, and hope this will help! If not you can accept my friend request on discord. _KiroKite#9999_

**Comment by nhulston** [comment]
Hi, thanks for letting me know.
1. As for the color codes, see this article: https://www.spigotmc.org/wiki/textcosmetics-colors-and-formats/
As far as I'm aware, Minecraft doesn't support custom color codes. But you can pick from the ones listed at that article. 
2. I understand you fixed it, but I'm just going to put the answer here in case someone else looks at this:
You need to download each extension. Example: /papi ecloud download Factions

**Comment by Kiro-playz** [comment]
The issue was I downloaded the wrong extension, but yeah. 

Minecraft java does support custom colours, I have used it in the past ( 2 days ago ), for all my ranks, as an example. So I had to reformat all my ranks for them to work with this plugin, which was time-consuming, if you can't do it, then it's fine, but if you can, it would be really helpful!
